#!/usr/bin/env bash

vendor/bin/spas run \
    --file "spas-input.apib.refract.json" \
    --type apib-refract \
    --base_uri http://localhost:8000 \
    --request_provider "\Hmaus\Spas\Parser\Apib"
